"""initial_schema

Revision ID: 179916335d1a
Revises: 
Create Date: 2026-07-10 20:26:34.794757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179916335d1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ab_tests_flag_id', table_name='ab_tests')
    op.create_index(op.f('ix_ab_tests_flag_id'), 'ab_tests', ['flag_id'], unique=False)
    op.drop_constraint('fk_ab_tests_winner_variant_id', 'ab_tests', type_='foreignkey')
    op.create_foreign_key(None, 'ab_tests', 'ab_variants', ['winner_variant_id'], ['id'])
    op.drop_index('idx_ab_variants_ab_test_id', table_name='ab_variants')
    op.create_index(op.f('ix_ab_variants_ab_test_id'), 'ab_variants', ['ab_test_id'], unique=False)
    op.drop_constraint('api_keys_key_hash_key', 'api_keys', type_='unique')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_project_id', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.drop_constraint('conversion_events_flag_id_fkey', 'conversion_events', type_='foreignkey')
    op.drop_constraint('conversion_events_ab_test_id_fkey', 'conversion_events', type_='foreignkey')
    op.create_foreign_key(None, 'conversion_events', 'ab_tests', ['ab_test_id'], ['id'])
    op.create_foreign_key(None, 'conversion_events', 'flags', ['flag_id'], ['id'])
    op.drop_index('idx_eval_events_timestamp', table_name='evaluation_events')
    op.create_index(op.f('ix_evaluation_events_timestamp'), 'evaluation_events', ['timestamp'], unique=False)
    op.drop_index('idx_flag_rules_flag_id', table_name='flag_rules')
    op.create_index(op.f('ix_flag_rules_flag_id'), 'flag_rules', ['flag_id'], unique=False)
    op.drop_index('idx_flags_project_id', table_name='flags')
    op.create_index(op.f('ix_flags_project_id'), 'flags', ['project_id'], unique=False)
    op.drop_index('idx_projects_owner_id', table_name='projects')
    op.drop_index('idx_projects_slug', table_name='projects')
    op.drop_constraint('projects_slug_key', 'projects', type_='unique')
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.create_unique_constraint('projects_slug_key', 'projects', ['slug'])
    op.create_index('idx_projects_slug', 'projects', ['slug'], unique=True)
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_flags_project_id'), table_name='flags')
    op.create_index('idx_flags_project_id', 'flags', ['project_id'], unique=False)
    op.drop_index(op.f('ix_flag_rules_flag_id'), table_name='flag_rules')
    op.create_index('idx_flag_rules_flag_id', 'flag_rules', ['flag_id'], unique=False)
    op.drop_index(op.f('ix_evaluation_events_timestamp'), table_name='evaluation_events')
    op.create_index('idx_eval_events_timestamp', 'evaluation_events', ['timestamp'], unique=False)
    op.drop_constraint(None, 'conversion_events', type_='foreignkey')
    op.drop_constraint(None, 'conversion_events', type_='foreignkey')
    op.create_foreign_key('conversion_events_ab_test_id_fkey', 'conversion_events', 'ab_tests', ['ab_test_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('conversion_events_flag_id_fkey', 'conversion_events', 'flags', ['flag_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index('idx_api_keys_project_id', 'api_keys', ['project_id'], unique=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=True)
    op.create_unique_constraint('api_keys_key_hash_key', 'api_keys', ['key_hash'])
    op.drop_index(op.f('ix_ab_variants_ab_test_id'), table_name='ab_variants')
    op.create_index('idx_ab_variants_ab_test_id', 'ab_variants', ['ab_test_id'], unique=False)
    op.drop_constraint(None, 'ab_tests', type_='foreignkey')
    op.create_foreign_key('fk_ab_tests_winner_variant_id', 'ab_tests', 'ab_variants', ['winner_variant_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_ab_tests_flag_id'), table_name='ab_tests')
    op.create_index('idx_ab_tests_flag_id', 'ab_tests', ['flag_id'], unique=False)
    # ### end Alembic commands ###
